### ISSUE TITLE
能否新增oidc的demo

### ISSUE THREAD

**Issue by mengxzh** [ZhiQinIsZhen/dubbo-springboot3#1]

**Comment by ZhiQinIsZhen** [comment]
有什么不清楚的可以交流，这个应该配置下可以直接跑起来，里面打个断点应该就明白了

**Comment by ZhiQinIsZhen** [comment]
> _No description provided._

有什么不清楚的可以交流，这个应该配置下可以直接跑起来，里面打个断点应该就明白了

**Comment by mengxzh** [comment]
就是oauth2的鉴权流程

**Comment by ZhiQinIsZhen** [comment]
> 就是oauth2的鉴权流程

这个还是和oauth2有些区别，这个没有重定向，流程的图在https://github.com/ZhiQinIsZhen/dubbo-springboot3/blob/main/document   这个下面
