### ISSUE TITLE
是否可以添加部署相关的文档内容

### ISSUE THREAD

**Issue by mrzhu666** [ZhiQinIsZhen/dubbo-springboot3#2]
整个项目的部署流程文档，添加docker文件等

**Comment by ZhiQinIsZhen** [comment]
> 整个项目的部署流程文档，添加docker文件等

现在基本都不会在项目中加dockerFile了，基本都是配置在k8s中，如果需要部署文档，可以补充一个

**Comment by mrzhu666** [comment]
> > 整个项目的部署流程文档，添加docker文件等
> 
> 现在基本都不会在项目中加dockerFile了，基本都是配置在k8s中，如果需要部署文档，可以补充一个

希望能补充，没部署文档弄起来要靠猜，比较麻烦

**Comment by ZhiQinIsZhen** [comment]
> > > 整个项目的部署流程文档，添加docker文件等
> > 
> > 
> > 现在基本都不会在项目中加dockerFile了，基本都是配置在k8s中，如果需要部署文档，可以补充一个
> 
> 希望能补充，没部署文档弄起来要靠猜，比较麻烦

已经添加
